name: Terraform Plan
description: Create a Terraform plan
inputs:
  dir:
    description: The source directory
    required: false
  out:
    description: The output file path of the generated plan
    required: false
  encrypt:
    description: Encrypt the generated plan
    required: false
  preview:
    description: Generate a markdown preview
    required: false
    default: 'off'
  artifact:
    description: Upload the plan as an artifact
    required: false
outputs:
  dir:
    description: The source directory
  out:
    description: The output file path of the generated plan
  preview:
    description: The markdown preview of the plan
  artifact:
    description: The name of the uploaded artifact
runs:
  using: node12
  main: dist/index.js
