name: Terraform Plan
description: Create a Terraform plan
inputs:
  dir:
    description: The source directory
    required: false
  out:
    description: The output file path of the generated plan
    required: false
  preview:
    description: Generate a markdown preview
    required: false
outputs:
  dir:
    description: The source directory
  out:
    description: The output file path of the generated plan
  preview:
    description: The markdown preview of the plan
runs:
  using: node12
  main: dist/index.js
